version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "develop-app"
s3_bucket = "app-deploy-bucket"
s3_prefix = "app-deploy-bucket"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"v1\" Env=\"develop\""
image_repositories = []
