version = 0.1

[develop]
[develop.deploy]
[develop.deploy.parameters]
stack_name = "develop-app"
s3_prefix = "develop-app"
s3_bucket = "sam-deploy-bucket"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"v1\" Env=\"develop\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-app"
s3_prefix = "staging-app"
s3_bucket = "sam-deploy-bucket"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"v1\" Env=\"staging\""
image_repositories = []
