service: app
frameworkVersion: '3'

custom:
  env: develop
  develop:
    region: ap-northeast-1

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 300
  stage: develop
  region: ap-northeast-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ec2:describeInstances"
            - "ec2:createImage"
            - "ec2:createTags"
            - "ec2:describeImages"
            - "ec2:deregisterImage"
            - "ec2:deleteSnapshot"
          Resource: "*"

  environment:
    NODE_ENV: ${self.custom.env}
    AMI_RETENTION_PERIOD: 2

package:
  patterns:
    - '!package*.json'
    - '!event*.json'
    - '!test/**'
    - '!docs/**'

functions:
  create-ami:
    handler: index.handler
    events:
      - schedule:
          rate: cron(50 19 * * ? *)
          name: develop-create-ami
