AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for triggering AWS Lambda Functions via scheduled CloudWatch events.

Parameters:
  Env:
    Type: String
    AllowedValues:
      - develop
      - staging

Resources:
  CreateAMI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Env}-create-ami
      CodeUri: app
      Handler: index.handler
      Timeout: 300
      Runtime: nodejs18.x
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "ec2:describeInstances"
              - "ec2:createImage"
              - "ec2:createTags"
              - "ec2:describeImages"
              - "ec2:deregisterImage"
              - "ec2:deleteSnapshot"
            Resource: '*'
      Environment:
        Variables:
          ENV: !Sub ${Env}
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Name: !Sub ${Env}-create-ami
            Description: Daily Create AMI
            Schedule: cron(40 17 * * ? *)
