version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-states-cron"
s3_prefix = "sam-states-cron"
s3_bucket = "sam-deploy-bucket"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "StageName=\"v1\" Env=\"develop\" ExportBucket=\"cloudwatch-logs-bucket\""
image_repositories = []
